name: sortfood
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  intl: ^0.19.0
  quickalert: ^1.1.0
  path_provider: ^2.0.11
  table_calendar: ^3.0.7
  logger: ^1.1.0
  path: ^1.8.3
  google_fonts: 6.1.0
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.7.6
  google_sign_in_platform_interface: 2.4.2
  google_sign_in_web: 0.12.1
  image_picker: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - lib/assets/.env
   - lib/assets/icon/
